name: Daily Python Script

on:
  schedule:
    - cron: '0 17 * * *'  # This schedules the workflow to run every day at 12 pm EST (17:00 UTC)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add this line if you have dependencies

    - name: Run Python script
      run: python workflow.py 

    - name: commit files
      run: |
          git config --local user.email "totreywood@aol.com"
          git config --local user.name "treywood10"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
